server:
  error:
    include-stacktrace: never
    include-message: never
spring:
  config:
    import: optional:file:env.yml
  profiles:
    active: ${profile}
  datasource:
    url: jdbc:h2:file:./database
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
admin:
  username: ${username}
  password: ${password}